### ISSUE TITLE
secuer looking for missing yaml file

### ISSUE THREAD

**Issue by markddesimone** [nanawei11/Secuer#1]
``` 
secuer S -i /media/mark/ssd2/temp/sctest.tsvTraceback (most recent call last):
  File "/home/mark/miniconda3/envs/scvi/bin/secuer", line 8, in <module>
    sys.exit(main())
  File "/home/mark/miniconda3/envs/scvi/lib/python3.8/site-packages/console/secuer_console.py", line 137, in main
    params = get_yaml_load_all(args.yamlpath)
  File "/home/mark/miniconda3/envs/scvi/lib/python3.8/site-packages/console/secuer_console.py", line 19, in get_yaml_load_all
    with open(yaml_file, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test.yaml'
```

I can find no reference to the yaml file at https://pypi.org/project/secuer/1.0.7/ and can find no other instructions

**Comment by nanawei11** [comment]
Hello, thanks for your question. If you want to run our method from the command line, you will need to download the YAML file from [here](https://github.com/nanawei11/Secuer/blob/main/config.yaml). Then run as follows：

```
Secuer S -i ./example_data/Biase_k3_FPKM_scRNA.csv --yaml <your path of yaml file>/config.yaml -o ./ -p 1000 --knn 5 --transpose
```
where the example data can be downloaded from [here](https://github.com/nanawei11/Secuer/blob/main/example_data/Biase_k3_FPKM_scRNA.csv).

We hope that would be useful for you.

**Comment by markddesimone** [comment]
Thank you, very helpful
